### ISSUE TITLE
Errors when trying to use the "Edit" button on a filled EntityReference field

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/entityconnect#1]
>  Notice: Trying to get property 'data' of non-object in entityconnect_edit() (line 180 of /code/modules/contrib/entityconnect/includes/entityconnect.menu.inc).

>  Notice: Trying to get property 'data' of non-object in entityconnect_edit() (line 181 of /code/modules/contrib/entityconnect/includes/entityconnect.menu.inc).

>  Exception: Entity type can not be empty in entityconnect_entityconnect_edit_info() (line 236 of /code/modules/contrib/entityconnect/includes/entityconnect.menu.inc).

> **Entity type can not be empty**

**Comment by laryn** [comment]
Similar errors when using the "Add" button, but line numbers 43, 44, and 96.

**Comment by laryn** [comment]
I think I found it -- a case where a constant was misinterpreted as text (probably by Coder Upgrade). PR coming.

**Comment by oadaeh** [comment]
Excellent! I had run into that, too, but I was barking up the wrong tree (and then I didn't have time to get back to it). I don't how long it would have taken me to figure out your fix.
