### ISSUE TITLE
Add me as co-maintainer?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/entityconnect#3]
@oadaeh Would you like a co-maintainer? If so, I may be able to pitch in and help get an initial release. I'm using this on a site and prefer to have an official release where possible to better keep track of which version is in use.

**Comment by oadaeh** [comment]
Hi @laryn. I don't mind adding you as a co-maintainer, but the reason it doesn't have an official release is because GitHub was giving me troubles with creating one. However, I just tried it again, and it worked, so there is now a 1.x-2.0.0 release.

**Comment by oadaeh** [comment]
And it's even "official": https://backdropcms.org/project/entityconnect
