### ISSUE TITLE
Field settings don't save / don't override defaults

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/entityconnect#4]
That's my first look at this promising module. If I don't miss anything, I'm not able to override the general settings for individual fields.

Whatever Buttons or Icon display parameters I set on a Entity Reference autocomplete field, they are not saved when I save the field settings, so they don't override the settings from `admin/config/content/entityconnect`. This is especially problematic, as the Buttons are set to "Off" by default.

**Comment by oadaeh** [comment]
Thank you for bringing this issue up.

When I was first porting and testing the module, I did not see that behavior, but when I tried to use it on a site, I did notice something similar (if not the same), but I haven't had a chance to troubleshoot it yet. I will try to do that soon, but I have quite a full schedule right now, and so "soon" might not be until the end of June.

Thanks again.

**Comment by keiserjb** [comment]
I installed the module and thought I needed to alter the settings for the field on the content type I wanted to use it on.  Turns out I need to change it at admin/config/content/entityconnect instead.  Then it works for me.  
![image](https://user-images.githubusercontent.com/41843284/169577859-21aa4ef3-f451-4e96-8b2a-886ec9ef7309.png)

I don't seem to be able to change the settings by field though.

**Comment by oadaeh** [comment]
Thanks for pointing that out, @keiserjb. I just saw that behavior myself, and I'm pretty sure it's incorrect. I'm pretty sure those are supposed to be default behaviors that can be overridden on a per field basis. I need to look at the code when I'm not ready to pass out and figure out what's going on, but now that I have a good idea what's going on, I should be able to figure it out pretty quickly.

**Comment by oadaeh** [comment]
It wasn't as simple to figure out as I initially imagined it being, but I finally found the problem and committed the changes to the dev branch. Check it out and let me know if it works for you, and if it does, I'll tag a new release.

**Comment by olafgrabienski** [comment]
@oadaeh Many thanks for the fix. I've applied the last two commits to a test site, and it works for me, i.e. I'm able to override the general module settings per individual field.
