### ISSUE TITLE
Hide unported/unusable modules?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/entityconnect#5]
This shows on the install screen through the project installer. It would look more friendly to hide the submodules that aren't ported or usable:
![2022-05-14_23-53](https://user-images.githubusercontent.com/871421/168457844-ebb955e2-d9c4-4080-91ee-c1e4bd0a89df.png)

**Comment by oadaeh** [comment]
I have committed the changes for this in commit ab6d0775f2bbdeab96821f2e500c69068be7a87f. I'll tag a new release after I take care of #4.
