### ISSUE TITLE
Icons need height/width set

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/entityconnect#6]
This commit removes a `16px` height and width on the add/edit icons which is causing them to be completely hidden on my site. Adding that back makes the icons visible again.

https://github.com/backdrop-contrib/entityconnect/commit/bba01f27b2488bfbd6bdb2a834e508353aa1f71c

**Comment by oadaeh** [comment]
Hmm, I removed those because they weren't displaying correctly, and that fixed it for me. I'll have to see if maybe something else is/was interfering and causing my problem.

**Comment by oadaeh** [comment]
I have committed the changes for this in commit dfded6a2ce2589680241f075bce67778994a8f54. I'll tag a new release after I take care of #4.
