### ISSUE TITLE
Fatal error when Drupal compatibility layer is off

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entityconnect#7]
Entity Connect uses the deprecated Drupal callback `element_validate_integer` in function  `_entityconnect_admin_form()`. This causes the site to crash when saving the admin form for Entity Connect, when the Drupal compatibility layer is disabled.

Instead of using this callback, according to a [change record](https://docs.backdropcms.org/node/43955), Entity Connect should use a `number` form element.

**Comment by argiepiano** [comment]
PR #7 provided.

**Comment by oadaeh** [comment]
Thanks for reporting this and providing a fix.
